import type { ImageLike, PixelData, PixelmatchOptions, PixelmatchResult } from './types.js';
import { buildResult, validateInput } from './validate.js';

export type { ImageLike, PixelData, PixelmatchOptions, PixelmatchResult } from './types.js';

interface WasmMatchResult {
  readonly diff_count: number;
  readonly aa_count: number;
  readonly identical: boolean;
  [Symbol.dispose](): void;
}

interface WasmBindings {
  default: (wasmUrl?: string | URL) => Promise<void>;
  pixelmatch_wasm: (
    img1: PixelData,
    img2: PixelData,
    output: PixelData,
    width: number,
    height: number,
    threshold: number,
    detectAntiAliasing: boolean,
    alpha: number,
    aaR: number,
    aaG: number,
    aaB: number,
    diffR: number,
    diffG: number,
    diffB: number,
    hasAlt: boolean,
    altR: number,
    altG: number,
    altB: number,
    diffMask: boolean,
  ) => WasmMatchResult;
  pixelmatch_wasm_count: (
    img1: PixelData,
    img2: PixelData,
    width: number,
    height: number,
    threshold: number,
    detectAntiAliasing: boolean,
    alpha: number,
    aaR: number,
    aaG: number,
    aaB: number,
    diffR: number,
    diffG: number,
    diffB: number,
    hasAlt: boolean,
    altR: number,
    altG: number,
    altB: number,
    diffMask: boolean,
  ) => WasmMatchResult;
}

let bg: WasmBindings | null = null;

export async function initialize(wasmUrl?: string | URL): Promise<void> {
  // Dynamic import of wasm-pack generated bindings — the module path is not
  // resolvable at compile time (it's generated by wasm-pack at build time).
  bg = await (import('../wasm/pixelmatch_bg.js' as string) as Promise<WasmBindings>);
  await bg.default(wasmUrl);
}

export default function pixelmatch(
  img1: ImageLike,
  img2: ImageLike,
  options: PixelmatchOptions = {},
): PixelmatchResult {
  if (!bg) throw new Error('WASM not initialised. Call initialize() first.');

  const {
    threshold = 0.1,
    detectAntiAliasing = true,
    alpha = 0.1,
    aaColor = [255, 255, 0],
    diffColor = [255, 0, 0],
    diffColorAlt,
    diffMask = false,
    output,
  } = options;

  validateInput(img1, img2, output);

  const { data: data1, width, height } = img1;
  const { data: data2 } = img2;
  const totalPixels = width * height;

  const [aaR, aaG, aaB] = aaColor;
  const [diffR, diffG, diffB] = diffColor;
  const hasAlt = !!diffColorAlt;
  const [altR, altG, altB] = diffColorAlt || diffColor;

  using raw = output
    ? bg.pixelmatch_wasm(
        data1,
        data2,
        output,
        width,
        height,
        threshold,
        detectAntiAliasing,
        alpha,
        aaR,
        aaG,
        aaB,
        diffR,
        diffG,
        diffB,
        hasAlt,
        altR,
        altG,
        altB,
        diffMask,
      )
    : bg.pixelmatch_wasm_count(
        data1,
        data2,
        width,
        height,
        threshold,
        detectAntiAliasing,
        alpha,
        aaR,
        aaG,
        aaB,
        diffR,
        diffG,
        diffB,
        hasAlt,
        altR,
        altG,
        altB,
        diffMask,
      );

  return buildResult(raw.diff_count, raw.aa_count, totalPixels, raw.identical);
}
