import type { PixelData, PixelmatchOptions } from './pixelmatch.js';

export type { PixelData, PixelmatchOptions } from './pixelmatch.js';

interface WasmBindings {
  default: (wasmUrl?: string | URL) => Promise<void>;
  pixelmatch_wasm: (
    img1: PixelData,
    img2: PixelData,
    output: PixelData,
    width: number,
    height: number,
    threshold: number,
    includeAA: boolean,
    alpha: number,
    aaR: number,
    aaG: number,
    aaB: number,
    diffR: number,
    diffG: number,
    diffB: number,
    hasAlt: boolean,
    altR: number,
    altG: number,
    altB: number,
    diffMask: boolean,
  ) => number;
  pixelmatch_wasm_count: (
    img1: PixelData,
    img2: PixelData,
    width: number,
    height: number,
    threshold: number,
    includeAA: boolean,
    alpha: number,
    aaR: number,
    aaG: number,
    aaB: number,
    diffR: number,
    diffG: number,
    diffB: number,
    hasAlt: boolean,
    altR: number,
    altG: number,
    altB: number,
    diffMask: boolean,
  ) => number;
}

let bg: WasmBindings | null = null;

export async function initialize(wasmUrl?: string | URL): Promise<void> {
  // Dynamic import of wasm-pack generated bindings — the module path is not
  // resolvable at compile time (it's generated by wasm-pack at build time).
  bg = await (import('../wasm/pixelmatch_bg.js' as string) as Promise<WasmBindings>);
  await bg.default(wasmUrl);
}

export default function pixelmatch(
  img1: PixelData,
  img2: PixelData,
  output: PixelData | null | undefined,
  width: number,
  height: number,
  options: PixelmatchOptions = {},
): number {
  if (!bg) throw new Error('WASM not initialised. Call initialize() first.');

  const {
    threshold = 0.1,
    includeAA = false,
    alpha = 0.1,
    aaColor = [255, 255, 0],
    diffColor = [255, 0, 0],
    diffColorAlt,
    diffMask = false,
  } = options;

  const [aaR, aaG, aaB] = aaColor;
  const [diffR, diffG, diffB] = diffColor;
  const hasAlt = !!diffColorAlt;
  const [altR, altG, altB] = diffColorAlt || diffColor;

  if (output) {
    return bg.pixelmatch_wasm(
      img1,
      img2,
      output,
      width,
      height,
      threshold,
      includeAA,
      alpha,
      aaR,
      aaG,
      aaB,
      diffR,
      diffG,
      diffB,
      hasAlt,
      altR,
      altG,
      altB,
      diffMask,
    );
  }

  return bg.pixelmatch_wasm_count(
    img1,
    img2,
    width,
    height,
    threshold,
    includeAA,
    alpha,
    aaR,
    aaG,
    aaB,
    diffR,
    diffG,
    diffB,
    hasAlt,
    altR,
    altG,
    altB,
    diffMask,
  );
}
